_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 3
                - 5
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 3
                - 5
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 6
epochs:
    value: 50
learning_rate:
    value: 0.0001
model:
    value: Transformer
